volumes:
  keycloak-postgres-microservice-data:   
  postgres-identity-microservice-db-ui-data:

services:
  keycloak:
    # restart: always
    container_name: localhost
    image: quay.io/keycloak/keycloak:25.0
    command: start
    environment:
      KC_HOSTNAME: keycloak
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres.identity.db/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - postgres.identity.db
  postgres.identity.db:
    image: postgres:16.2
    container_name: postgres.identity.db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - keycloak-postgres-microservice-data:/var/lib/postgresql/data
  postgres.identity.db.ui:
    image: dpage/pgadmin4
    container_name: postgres.identity.db.ui
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - postgres-identity-microservice-db-ui-data:/var/lib/pgadmin